version: '3'

services:

  postgres:
    image: postgres:15.4-alpine3.18
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - internal
    environment:
      POSTGRES_USER: potato
      POSTGRES_PASSWORD: potato

networks:
  internal:
    external: true